import { db } from "@/db";
import { projects, tasks, ideas, activities, users, bomItems, workspaces } from "@/db/schema";
import { eq } from "drizzle-orm";
import PDFDocument from "pdfkit";
import { sendEmail, isEmailConfigured, EmailConfigError } from "./email";
import { formatDate } from "./utils";

const BRAND = "#2A5DD9";
const INK = "#14171A";
const MUTED = "#6B7280";
const LINE = "#E2E4E1";

export async function generateReportPdf(from: Date, to: Date): Promise<Buffer> {
  const [allProjects, allTasks, allIdeas, periodActivity, allUsers, allBom] = await Promise.all([
    db.select().from(projects),
    db.select().from(tasks),
    db.select().from(ideas),
    db.select().from(activities),
    db.select().from(users).where(eq(users.status, "active")),
    db.select().from(bomItems),
  ]);

  const inRange = (d: Date | null) => !!d && d >= from && d <= to;

  const projectsCompleted = allProjects.filter((p) => p.status === "completed" && inRange(p.updatedAt));
  const projectsStarted = allProjects.filter((p) => inRange(p.createdAt));
  const ideasCreated = allIdeas.filter((i) => inRange(i.createdAt));
  const tasksCompleted = allTasks.filter((t) => t.status === "done" && inRange(t.updatedAt));
  const blocked = allProjects.filter((p) => p.status === "blocked");
  const bomSpend = allBom
    .filter((b) => inRange(b.createdAt))
    .reduce((sum, b) => sum + (b.unitCost ?? 0) * b.quantity, 0);
  const recentActivity = periodActivity.filter((a) => inRange(a.createdAt)).slice(0, 15);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 0, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;
    const margin = 48;
    const contentWidth = pageWidth - margin * 2;

    // Header band
    doc.rect(0, 0, pageWidth, 110).fill(BRAND);
    doc.fillColor("#ffffff").fontSize(20).font("Helvetica-Bold").text("R&D Command Center", margin, 36);
    doc.fontSize(12).font("Helvetica").text("Weekly Report", margin, 62);
    doc.fontSize(10).fillColor("#dbe4ff").text(`${formatDate(from)}  —  ${formatDate(to)}`, margin, 80);

    let y = 140;

    function sectionTitle(text: string) {
      doc.fillColor(INK).font("Helvetica-Bold").fontSize(13).text(text, margin, y);
      y += 20;
      doc.moveTo(margin, y - 6).lineTo(pageWidth - margin, y - 6).strokeColor(LINE).lineWidth(1).stroke();
    }

    function statRow(label: string, value: string | number) {
      doc.font("Helvetica").fontSize(11).fillColor(MUTED).text(label, margin, y, { continued: false, width: contentWidth - 100 });
      doc.font("Helvetica-Bold").fontSize(11).fillColor(INK).text(String(value), margin, y, { width: contentWidth, align: "right" });
      y += 20;
    }

    function bodyLine(text: string, color = INK) {
      doc.font("Helvetica").fontSize(10.5).fillColor(color).text(text, margin, y, { width: contentWidth });
      y += doc.heightOfString(text, { width: contentWidth }) + 6;
    }

    sectionTitle("Overview");
    y += 4;
    statRow("Projects completed", projectsCompleted.length);
    statRow("Projects started", projectsStarted.length);
    statRow("Ideas created", ideasCreated.length);
    statRow("Tasks completed", tasksCompleted.length);
    statRow("Currently blocked", blocked.length);
    statRow("BOM spend this period", `Rs. ${bomSpend.toLocaleString("en-IN")}`);
    y += 16;

    sectionTitle("Blockers");
    y += 4;
    if (blocked.length === 0) {
      bodyLine("Nothing blocked right now.", MUTED);
    } else {
      blocked.forEach((p) => bodyLine(`• ${p.name}${p.blockedReason ? " — " + p.blockedReason : ""}`));
    }
    y += 12;

    sectionTitle("Team Workload (open tasks)");
    y += 4;
    allUsers.forEach((u) => {
      const open = allTasks.filter((t) => t.assigneeId === u.id && t.status !== "done").length;
      statRow(u.name, open);
    });
    y += 16;

    sectionTitle("Activity in this period");
    y += 4;
    if (recentActivity.length === 0) {
      bodyLine("No activity logged in this period.", MUTED);
    } else {
      recentActivity.forEach((a) => bodyLine(`• ${a.message}`));
    }

    doc.fontSize(8).fillColor(MUTED).text(
      "Generated by R&D Command Center",
      margin,
      doc.page.height - 40,
      { width: contentWidth, align: "center" }
    );

    doc.end();
  });
}

// Checks the workspace's own timezone to fire specifically on Saturday
// evening (5-9pm local), rather than "every 7 days since last sent" which
// drifts to whatever day the server happened to be running on.
function isSaturdayEvening(timezone: string): boolean {
  try {
    const parts = new Intl.DateTimeFormat("en-US", {
      timeZone: timezone,
      weekday: "short",
      hour: "numeric",
      hour12: false,
    }).formatToParts(new Date());
    const weekday = parts.find((p) => p.type === "weekday")?.value;
    const hour = Number(parts.find((p) => p.type === "hour")?.value);
    return weekday === "Sat" && hour >= 17 && hour < 21;
  } catch {
    return false;
  }
}

const MIN_HOURS_BETWEEN_REPORTS = 20;

export async function sendWeeklyReportIfDue() {
  if (!isEmailConfigured()) return;

  const [ws] = await db.select().from(workspaces).limit(1);
  if (!ws) return;
  if (!isSaturdayEvening(ws.timezone)) return;

  const lastSent = ws.lastWeeklyReportSentAt;
  if (lastSent && Date.now() - lastSent.getTime() < MIN_HOURS_BETWEEN_REPORTS * 60 * 60 * 1000) return;

  const admins = await db.select().from(users).where(eq(users.role, "admin"));
  if (admins.length === 0) return;

  const to = new Date();
  const from = new Date(to.getTime() - 7 * 24 * 60 * 60 * 1000);
  const pdf = await generateReportPdf(from, to);

  for (const admin of admins) {
    try {
      await sendEmail(
        admin.email,
        "Your Weekly R&D Report",
        `<div style="font-family: sans-serif;"><p>Your weekly R&D report is attached.</p></div>`,
        [{ filename: "weekly-report.pdf", content: pdf }]
      );
    } catch (err) {
      if (!(err instanceof EmailConfigError)) {
        console.error(`Failed to send weekly report to ${admin.email}:`, err);
      }
      return;
    }
  }

  await db.update(workspaces).set({ lastWeeklyReportSentAt: new Date() }).where(eq(workspaces.id, ws.id));
}
